chore: update workflows to use newer versions
googlemaps/google-maps-services-js pull request #1046
Opened 2023-10-09 09:45 UTC by usefulthink

With the new versions of dependencies, building the docs in node 10.x no longer works, so this is switched to current LTS. For the other workflows, newer versions of the `checkout` and `setup-node` actions are used.

2023-12-06 00:12 UTC, wangela requested changes

2023-12-06 00:12 UTC, wangela commented on .github/workflows/release.yml
The semantic release will fail as is. We can update the versions to match what I just did in js-url-signature: https://github.com/googlemaps/js-url-signature/pull/455/files

2023-12-06 12:48 UTC, usefulthink commented on .github/workflows/release.yml
Copied over all version numbers, I think we can give it a try.

2023-12-11 22:56 UTC, wangela approved these changes

2023-12-11 23:32 UTC, merged