add client_id and client_secret auth alternatives
googlemaps/google-maps-services-js pull request #640
Opened 2021-09-11 01:40 UTC by noahw3

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #639

I have not updated the tests, changelog, or version yet. I wanted to get feedback on the overall approach first.

The approach that I've taken is adding a special case in the `serializer` method that checks the params passed in. If `client_id` and `client_secret` are present it'll do the appropriate encoding and attachment/removal of query params.

Because the current implementation just passes all given parameters straight through to Axios this seemed like the most straightforward place to put this logic. Since this is common logic it felt appropriate to try and keep it in a common layer rather than needing to add any special logic (or defining explicit serializer params) per function.

One possible alternative would be to add an additional param serializer (instead of modifying the existing one) and require callers to use that one. That seemed less ideal since that serializer would look almost identical, the other default parameters would then need to be specified as well (method and url), and overall it would require clients to understand somewhat more of the lower level details of this library.

Something could also potentially be done with Axios interceptors, but again that seems much more complicated as well.

2021-09-14 22:40 UTC, jpoehnelt commented
This seems like a clean way to implement it. I'll take another look more closely but so far it looks good.

2021-09-14 22:48 UTC, jpoehnelt requested changes

2021-09-14 22:48 UTC, jpoehnelt commented on src/common.ts
> + * The Google Maps Platform Premium Plan is no longer available for sign up or new customers. This option is
add `@deprecated`

2021-09-21 00:15 UTC, noahw3 commented
I added unit tests, since there are no CI environment variables set for premium plan params I didn't add any e2e tests. If we want e2e tests I can add them, provided CI env vars.

I didn't see a changelog to update, though I did add a section to the README.

2021-09-21 18:02 UTC, jpoehnelt approved these changes
LGTM!

2021-09-21 18:04 UTC, jpoehnelt commented
> I didn't see a changelog to update, though I did add a section to the README.

This will be generated from the commit message. https://semantic-release.gitbook.io/semantic-release/

> since there are no CI environment variables set for premium plan params I didn't add any e2e tests.

That's fine. I'm not sure I can even set this up without jumping through way too many hoops 😄 !

Looks like the CLA is all that is remaining. Please let me know if you have any questions on that.

2021-09-21 19:05 UTC, noahw3 commented
@googlebot I signed it!

2021-09-21 19:40 UTC, noahw3 commented
@jpoehnelt I think it should be good to go, I added a few more tests to try and make codecov happy.

2021-09-22 00:13 UTC, merged